name: Renovate

on:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extends: "config:base"
          baseBranches: "main"
          packageFiles: "pom.xml"
          automerge: true
          automergeType: "pr"
          commitMessagePrefix: "[git commit] "
          commitMessageTopic: "Dependency Updates"
          enableCommitAuthor: true

      
